#!/usr/bin/env bash
# A bash script that installs nginx on an ubuntu machine.
# This scripts also configures the default webpage served to be "Hello World!"
# When request url matches /redirect_me, it redirects to my youtube channel.

sudo apt-get update -y

sudo apt-get install nginx -y

sudo echo "Hello World!" > /var/www/index.html

sudo echo -e "server {
\tlisten 80 default_server;

\tlisten [::]:80;

\troot /var/www/html;

\tindex index.html index.htm index.nginx-debian.html;

\tserver_name _;

\trewrite 
}
" > /etc/nginx/sites-available/default

sudo service nginx reload
