#!/usr/bin/env bash
# A bash script that installs nginx on an ubuntu machine.
# This scripts also configures the default webpage served to be "Hello World!"
# When request url matches /redirect_me, it redirects to my youtube channel.

sudo apt-get update -y

sudo apt-get install nginx -y

echo "Hello World!" | sudo tee /var/www/index.html

NEW_RULE="\\\n\tlocation = /redirect_me {\n\t\t return 301 https://www.youtube.com/@sammykingx;\n\t}\n"

sudo sed -i "42i $NEW_RULE" /etc/nginx/sites-available/default

sudo service nginx reload
