#!/usr/bin/env bash
# configures a new HAproxy as a load balancer

# Install HAproxy on a server
apt-get -y update
apt-get -y install haproxy=1.6.\*

# Configure haproxy configuration file to distribute requests using a roundrobin algorithm
echo '
frontend danicortes.tech
        bind 0:80
        default_backend web_servers

backend web_servers
        balance roundrobin
        server 2304-web-01 35.196.3.110:80
        server 2304-web-02 34.74.150.12:80
' >> /etc/haproxy/haproxy.cfg

# Restart HAproxy service
service haproxy restart
